import { expandMoreOptions, focusFirstComposerTextarea } from './dom'
import type { TutorialStep } from './types'

const bookRoute =
  (suffix: string) =>
  (ctx: { bookId: string | null }): string | null =>
    ctx.bookId ? `/book/${ctx.bookId}${suffix}` : null

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'welcome',
    kind: 'modal',
    title: 'Welcome to Not A Book Club!',
    body: "Want a quick tour of where everything lives — adding books, tracking chapters, and how the spoiler-locked discussion works? You can always come back to this from Settings.",
  },
  {
    id: 'home-shelf',
    kind: 'spotlight',
    route: () => '/',
    target: '[data-tour="home-shelf"]',
    optionalTarget: true,
    title: 'Your shelf',
    body: "Every book your group is tracking shows up here, grouped by your reading status. Tap any book to jump into it.",
  },
  {
    id: 'add-book-button',
    kind: 'spotlight',
    route: () => '/',
    target: '[data-tour="add-book-button"]',
    advanceOn: 'click-target',
    title: 'Adding a book',
    body: "Tap here to add a new book to the group — search by title, or add one manually if it's not out there.",
  },
  {
    id: 'add-book-search',
    kind: 'spotlight',
    route: () => '/add-book',
    target: '[data-tour="add-book-search"]',
    title: 'Search or add manually',
    body: "Search pulls in a cover and author automatically. Can't find it? Type the title and add it manually instead — either way it lands on the group's shelf for everyone.",
  },
  {
    id: 'pick-book',
    kind: 'picker',
    shouldSkip: (ctx) => Boolean(ctx.bookId) || ctx.books.length === 0,
    title: 'Pick a book to continue the tour',
    body: "We'll use it to show you Chapters and Discussion.",
  },
  {
    id: 'book-tabs',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="book-tabs"]',
    title: "A book's tabs",
    body: "Overview for your reading status and progress, Discussion for the spoiler-locked thread, Chapters for the table of contents, Reviews once it's finished, and Covers for group-submitted art.",
  },
  {
    id: 'shelf-status',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="shelf-status"]',
    title: 'Your reading status',
    body: '"Reading now" and "Paused" track your chapter position. "Want to read" keeps it on your radar with no tracking yet. "Read before joining" unlocks the full thread immediately — it\'s for books your group picked after you\'d already read them. "Did not finish" does NOT unlock the thread by itself — you stay locked wherever you stopped unless you also check Spoil Me.',
  },
  {
    id: 'spoil-reread',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="spoil-reread"]',
    prepare: expandMoreOptions,
    optionalTarget: true,
    title: 'Rereading? It relocks the thread',
    body: 'Starting a reread resets your chapter position and takes away full access again, even though you already finished the book once. Check "View full thread anyway" if you still want to see ahead of your reread position.',
  },
  {
    id: 'current-chapter',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="current-chapter"]',
    optionalTarget: true,
    title: 'Your chapter position',
    body: "This drives everything spoiler-related — Discussion only shows you comments up to here, unless your status above grants full access.",
  },
  {
    id: 'add-chapter-live',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="add-chapter-live"]',
    optionalTarget: true,
    title: 'Adding chapters as you go',
    body: "Don't know the book's full chapter breakdown yet? Add one chapter at a time here as you finish each — it bumps your position automatically.",
  },
  {
    id: 'chapter-setup-panel',
    kind: 'spotlight',
    route: bookRoute('/chapters'),
    target: '[data-tour="chapter-setup-panel"]',
    optionalTarget: true,
    title: 'Setting up the whole table of contents',
    body: "Already know the book's structure? Paste the full table of contents here, one chapter per line — or quick-fill generic placeholders. All at once, instead of one at a time.",
  },
  {
    id: 'discussion-composer',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="chapter-top"]',
    optionalTarget: true,
    title: 'The Discussion thread',
    body: "Each chapter gets its own section with a header and a composer to share a thought, tagged to that chapter.",
  },
  {
    id: 'locked-chapter',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="locked-chapter"]',
    optionalTarget: true,
    title: "🔒 Chapters you haven't reached",
    body: "Anything past your current position collapses into a bar like this. Advancing your chapter position (not tapping anything here) is what clears it.",
  },
  {
    id: 'hidden-reveal',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="hidden-reveal"]',
    optionalTarget: true,
    title: '🙈 Hidden comments',
    body: "Even inside a chapter you've reached, other members' comments can stay tucked away until you tap Reveal — so you can post your own reaction first without theirs getting in the way.",
  },
  {
    id: 'prediction-checkbox',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="prediction-checkbox"]',
    prepare: focusFirstComposerTextarea,
    optionalTarget: true,
    title: '🔮 Marking a prediction',
    body: 'Guessing what happens next? Check this and your comment posts collapsed behind a "tap to reveal" line for everyone — including you later — so a right guess doesn\'t spoil anything.',
  },
  {
    id: 'spoiler-controls',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="no-spoilers-checkbox"]',
    prepare: focusFirstComposerTextarea,
    optionalTarget: true,
    title: '❓ "No spoilers please" vs. 🙈 "Insert spoiler"',
    body: '"No spoilers please" is just a flag — it narrows which chapter replies to your comment can be tagged to, but doesn\'t hide anything itself. "Insert spoiler" (further down) is the real lock: it hides just that bit of text from anyone who hasn\'t reached its chapter yet, even inside an otherwise-visible comment.',
  },
  {
    id: 'comment-actions',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="comment-actions"]',
    optionalTarget: true,
    title: 'Replying & reacting',
    body: "Reply tags your response to that comment, reactions are a quick tap, and Flag immediately hides a comment from everyone but its author and admins until it's retagged or removed.",
  },
  {
    id: 'invite-code',
    kind: 'spotlight',
    route: () => '/settings',
    target: '[data-tour="invite-code"]',
    title: 'Inviting people',
    body: "Share this code (or the copy-link button) to bring someone else into the group.",
  },
  {
    id: 'replay-tutorial',
    kind: 'spotlight',
    route: () => '/settings',
    target: '[data-tour="replay-tutorial"]',
    title: 'Replay anytime',
    body: "Forgot something? Come back here whenever you want to run through this again.",
  },
  {
    id: 'done',
    kind: 'modal',
    title: "You're all set!",
    body: "That's the whole tour — go add a book, pick a status, and start the discussion.",
  },
]
