import { expandMoreOptions, focusFirstComposerTextarea } from './dom'
import type { TutorialStep } from './types'

const bookRoute =
  (suffix: string) =>
  (ctx: { bookId: string | null }): string | null =>
    ctx.bookId ? `/book/${ctx.bookId}${suffix}` : null

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'welcome',
    kind: 'modal',
    title: 'Welcome to Not A Book Club!',
    body: 'Want a quick tour of adding books, chapters, and how the spoiler-locked discussion works? Replay anytime from Settings.',
  },
  {
    id: 'home-shelf',
    kind: 'spotlight',
    route: () => '/',
    target: '[data-tour="home-shelf"]',
    optionalTarget: true,
    title: 'Your shelf',
    body: "Every book your group's tracking, grouped by status. Tap one to jump in.",
  },
  {
    id: 'add-book-button',
    kind: 'spotlight',
    route: () => '/',
    target: '[data-tour="add-book-button"]',
    advanceOn: 'click-target',
    title: 'Adding a book',
    body: "Tap to add a book — search by title, or add one manually.",
  },
  {
    id: 'add-book-search',
    kind: 'spotlight',
    route: () => '/add-book',
    target: '[data-tour="add-book-search"]',
    title: 'Search or add manually',
    body: "Search pulls in a cover and author automatically — or type a title and add it manually.",
  },
  {
    id: 'pick-book',
    kind: 'picker',
    shouldSkip: (ctx) => Boolean(ctx.bookId) || ctx.books.length === 0,
    title: 'Pick a book',
    body: "We'll use it for Chapters and Discussion.",
  },
  {
    id: 'book-tabs',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="book-tabs"]',
    title: "A book's tabs",
    body: 'Overview for status & progress, Discussion for the thread, Chapters for the table of contents, Reviews, and Covers.',
  },
  {
    id: 'shelf-status',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="shelf-status"]',
    title: 'Your reading status',
    body: '"Read before joining" unlocks the full thread right away. "Did not finish" doesn\'t — you\'re still locked unless you also check Spoil Me.',
  },
  {
    id: 'spoil-reread',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="spoil-reread"]',
    prepare: expandMoreOptions,
    optionalTarget: true,
    title: 'Rereading? It relocks the thread',
    body: 'Starting a reread resets your position and relocks the thread. Check "View full thread anyway" to still see ahead.',
  },
  {
    id: 'current-chapter',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="current-chapter"]',
    optionalTarget: true,
    title: 'Your chapter position',
    body: "Discussion only shows comments up to here, unless your status grants full access.",
  },
  {
    id: 'add-chapter-live',
    kind: 'spotlight',
    route: bookRoute(''),
    target: '[data-tour="add-chapter-live"]',
    optionalTarget: true,
    title: 'Adding chapters as you go',
    body: "Don't know the full chapter breakdown yet? Add one at a time as you finish each.",
  },
  {
    id: 'chapter-setup-panel',
    kind: 'spotlight',
    route: bookRoute('/chapters'),
    target: '[data-tour="chapter-setup-panel"]',
    optionalTarget: true,
    title: 'Setting up the whole table of contents',
    body: "Know the book's structure already? Paste the whole table of contents here at once, or quick-fill placeholders.",
  },
  {
    id: 'discussion-composer',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="chapter-top"]',
    optionalTarget: true,
    title: 'The Discussion thread',
    body: "Each chapter gets its own section — share a thought here, tagged to it.",
  },
  {
    id: 'locked-chapter',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="locked-chapter"]',
    optionalTarget: true,
    title: "🔒 Chapters you haven't reached",
    body: "Chapters past your position collapse like this — advancing your position clears it, not tapping here.",
  },
  {
    id: 'hidden-reveal',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="hidden-reveal"]',
    optionalTarget: true,
    title: '🙈 Hidden comments',
    body: "Others' comments can stay hidden until you tap Reveal — so you can post your own reaction first.",
  },
  {
    id: 'prediction-checkbox',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="prediction-checkbox"]',
    prepare: focusFirstComposerTextarea,
    optionalTarget: true,
    title: '🔮 Marking a prediction',
    body: 'Guessing what happens next? This collapses your comment behind a "tap to reveal" line for everyone.',
  },
  {
    id: 'spoiler-controls',
    kind: 'spotlight',
    route: bookRoute('/thread'),
    target: '[data-tour="no-spoilers-checkbox"]',
    prepare: focusFirstComposerTextarea,
    optionalTarget: true,
    title: '❓ "No spoilers please" vs. 🙈 "Insert spoiler"',
    body: '"No spoilers please" just limits which chapters replies can tag. "Insert spoiler" (below) really hides that text until the reader catches up.',
  },
  {
    id: 'invite-code',
    kind: 'spotlight',
    route: () => '/settings',
    target: '[data-tour="invite-code"]',
    title: 'Inviting people',
    body: 'Share this code — or the copy-link button — to bring someone into the group.',
  },
  {
    id: 'replay-tutorial',
    kind: 'spotlight',
    route: () => '/settings',
    target: '[data-tour="replay-tutorial"]',
    title: 'Replay anytime',
    body: 'Come back here anytime to run through this again.',
  },
  {
    id: 'done',
    kind: 'modal',
    title: "You're all set!",
    body: 'Go add a book, pick a status, and start the discussion.',
  },
]
